name: 假行僧
description: false
meta_description: false

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         false

post_footer:  false